apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: compgrid-cluster
  region: us-east-1
  version: "1.27"

# IAM configuration
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

# Managed node groups
managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    privateNetworking: true
    labels:
      role: worker
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        cloudWatch: true

# Add-ons
addons:
  - name: aws-load-balancer-controller
    version: latest
  - name: amazon-cloudwatch-observability
    version: latest
